### ISSUE TITLE
Shape error in histogramdd

### ISSUE THREAD

**Issue by WilliamKorcari** [francois-rozet/torchist#1]
Hi, thank you for the nice package. I am experiencing an error that I cannot figure out while using the `histogramdd` function. I am making multiple histograms in a for-loop and I always feed the `histogramdd` function tensors of the same shape.

```python
>>> inputs = torch.stack([y[i], x[i], z[i]], -1)  # shape [4000, 3]
>>> weights = w[i]                                # shape [4000]
>>> h0 = torchist.histogramdd(inputs, edges=[30, 32, 30], weights=weights)
```

It works fine most of the time, but then it breaks all of a sudden with this kind of error:

```python
>>> h0 = torchist.histogramdd(inputs, edges=[30, 32, 30], weights=w[i])
File ".../torchist/__init__.py", line 225, in histogramdd
    hist = idx.bincount(weights, minlength=shape.numel()).view(shape)
RuntimeError: shape '[30, 32, 30]' is invalid for input of size 29358
```

Since the shape of what I feed in is always the same I am confused about what might be generating the error. It looks like `idx` has somehow the wrong shape, i.e. not 30x32x30. Or I am just misunderstanding something?

Edit: I am using version '0.1.8' and tensors are all CUDA tensors.

**Comment by francois-rozet** [comment]
Hello, thank you for the report. It seems like you are using `edges` instead of `bins` to define the shape of your histogram (30x32x30). The `edges` argument should be a tensor whose elements are the edges of each bins. If you wanted to divide the [0, 1] interval in 3 bins of width 0.25, 0.5 and 0.25 respectively, you would have

```python
edges = torch.tensor([0.0, 0.25, 0.75, 0.1])
```

In particular, the elements of `edges` should be **strictly increasing**. In your case, (I guess that) you want to divide the dimensions into, respectively, 30, 32 and 30 bins of uniform width. Then, you should use `bins` instead of `edges`:

```python
h0 = torchist.histogramdd(input, edges=[30, 32, 30], weights=weights)
```

Tell me if this helps. Note that I have just released a newer version (0.2.0) of the package.

**Comment by WilliamKorcari** [comment]
Thank you for your reply. I am sorry I misreported my code trying to reduce it to the minimum necessary amount. I actually use `edges` the proper way and the code looks like this

```python
>>> inputs = torch.stack([y[i], x[i], z[i]], -1)  # shape [4000, 3]
>>> weights = w[i]                                # shape [4000]
>>> edges = [torch.arange(31)*0.5250244140625, torch.arange(-81, 82, 5.088333), torch.arange(-77+5.088333*8, 78+5.088333*8, 5.088333)] # shape [31, 32, 31] and strictly increasing. 
>>> h0 = torchist.histogramdd(inputs, edges=edges, weights=weights)
```

I also adjusted the edges to have the same size [31,31,31], even though by reading your nice code I found it should not be necessary and the code still "randomly" fails. I also looked at the tensors that cause the break, but they have nothing special with respect to the others (all `float` tensors, no `NaN`).

After spending some time trying to figure out what is going on, I guessed that maybe something goes wrong with the `torch.searchsorted` method because from the error I posted the value `29358` is clearly bigger than 30x32x30 = 28800 but I don't understand where such value could be coming from.

I will try the updated version too, in order to see if this is sorted out. Thanks again for any help you can provide :)

**Comment by francois-rozet** [comment]
Ok this seems like a bug, I will look into it. However, I notice that your bins have a uniform width. So instead of using `edges` you can provide `bins`, `low` and `upp`. This should fix the issue as the `quantize` function does not rely on `searchsorted`.

**Comment by WilliamKorcari** [comment]
Thank you for the tip!
