### ISSUE TITLE
Assertion error with lower/upper bound lists

### ISSUE THREAD

**Issue by yanconglin** [francois-rozet/torchist#2]
### Description

bug 1: [assert torch.all(upp > low), "The upper bound must be strictly larger than the lower bound"](https://github.com/francois-rozet/torchist/blob/ee7dfc7e4eb440a8e5b204dddbfb0864438c411b/torchist/__init__.py#L152)
```
    print(torch.all(upp > low), upp>low)
TypeError: all(): argument 'input' (position 1) must be Tensor, not bool
```

bug 2: func quantize: 
[quantize](https://github.com/francois-rozet/torchist/blob/ee7dfc7e4eb440a8e5b204dddbfb0864438c411b/torchist/__init__.py#L69)
```
    x = torch.clip(x, min=0, max=bins - 1)  # in [0, bins)
TypeError: clip() received an invalid combination of arguments - got (Tensor, max=Tensor, min=int), but expected one of:
 * (Tensor input, Tensor min, Tensor max, *, Tensor out)
 * (Tensor input, Number min, Number max, *, Tensor out)
 ```

### Reproduce
bug 1: happens when low/upp is a list/sequence of scalars. torch.all requires tensor inputs, otherwise the output is False by default.
```
    t_hist = torchist.histogramdd(t_tensor, bins =[64, 64, 32], 
                                  low=[-a, -b, -c],  # variable low is a list/sequence of scalars
                                  upp=[a, b, c] # variable low is a list/sequence of scalars
                                  )
```
bug 2: bug2 appears after bug 1, because 'max=bins-1' is a tensor while 'min=0' is not.

Will add a minimal example later. Perhaps a pytorch version issue?

### Causes and solution
To fix:
bug 1: asset func stays after as_tensors;
```
    bins = torch.as_tensor(bins).squeeze().long()
    low = torch.as_tensor(low).squeeze().to(x)
    upp = torch.as_tensor(upp).squeeze().to(x)

    assert torch.all(upp > low), "The upper bound must be strictly larger than the lower bound"
```
bug 2: replace 'min=0' by 'min=x.new_zeros(bins.numel())'
```
x = torch.clip(x, min=x.new_zeros(bins.numel()), max=bins - 1)  # in [0, bins)
```
### Environment

* torchist version: [0.2.0]
* PyTorch version: [1.12.0]
* Python version: [3.9.16]
* OS: [Ubuntu 22.04]

**Comment by yanconglin** [comment]
BTW, having the same issue as in [issue 1](https://github.com/francois-rozet/torchist/issues/1#issue-1606739814). Using the  "edges" option fails sometimes ....

**Comment by francois-rozet** [comment]
Hello @yanconglin, thanks for the bug report! I will soon merge a PR (#3) to fix them. I was never able to reproduce the issue of #1, so could not fix it. If you have a minimal example, I could give it a try!
